### ISSUE TITLE
font update

### ISSUE THREAD

**Issue by evanwill** [uidaholib/collectionbuilder-sa-spec-exhibits#2]
merge updates from main and deploy to server:

- [x] main
- [x] 1918flu
- [x] coursecatalogs
- [x] dodson
- [x] ernieday
- [x] hiroshima
- [x] lrcdp
- [x] shitamae

**Comment by owikle** [comment]
@kxuidaho ignore dukesilver, dukesilver2, and uiblackhistory (check digital_all_collections spreadsheet tab spec-sa for an up to date list)
